apiVersion: apps/v1
kind: Deployment
metadata:
  name: stackport-deployment
  labels:
    com.job.service: stackport
spec:
  selector:
    matchLabels:
      com.job.service: stackport
  replicas: 1
  template:
    metadata:
      labels:
        com.job.service: stackport
    spec:
      serviceAccountName: default
      containers:
      - name: stackport
        image: davireis/stackport:latest
        env:
          - name: AWS_ENDPOINT_URL
            value: "http://localstack-service:4566"
          - name: AWS_REGION
            value: "us-east-1"
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-credentials
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-credentials
                key: AWS_SECRET_ACCESS_KEY
          # Opcional: definir a porta que o StackPort usa internamente (padrão é 8080)
          - name: PORT
            value: "8080"
        ports:
        - containerPort: 8080