apiVersion: v1
kind: Service
metadata:
  name: stackport
  labels:
    com.job.service: stackport
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30006
  selector:
    com.job.service: stackport