apiVersion: v1
kind: Service
metadata:
  name: stackport-service
  labels:
    com.job.service: stackport-service
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30006   # Escolha uma porta livre no seu Minikube
  selector:
    com.job.service: stackport