apiVersion: v1
kind: Service
metadata:
  name: dynamodb-admin-service
  labels:
    com.job.service: dynamodb-admin-service
spec:
  type: NodePort
  ports:
  - port: 8001
    targetPort: 8001
    nodePort: 30005
  selector:
    com.job.service: dynamodb-admin
