apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
data:
  config.yaml: |
    extensions:
      health_check:
        endpoint: 0.0.0.0:13133

    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch:
        timeout: 1s
        send_batch_size: 1024

    exporters:
      debug:
        verbosity: detailed
      prometheus:
        endpoint: "http://prometheus-service:8889"
      loki:
        endpoint: "http://loki-service:3100/loki/api/v1/push"
      tempo:
        endpoint: "http://tempo-service:3200"
        tls:
          insecure: true

    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug, tempo]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug, prometheus]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug, loki]




