apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      mysql:
        endpoint: mysql:3306
        username: "root"
        password: "${env:MYSQL_PASSWORD}"
        collection_interval: 10s

    processors:
      memory_limiter:
        check_interval: 1s
        limit_mib: 512
      batch:
        send_batch_size: 1000
        timeout: 1s

    exporters:
      debug:
        verbosity: normal

      zipkin:
        endpoint: "http://zipkin:9411/api/v2/spans"
        format: "json"
      
      prometheus:
        endpoint: 0.0.0.0:8889
        send_timestamps: true
        metric_expiration: 180m
        resource_to_telemetry_conversion:
          enabled: true

    extensions:
      health_check:
        endpoint: 0.0.0.0:13133

    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [zipkin, debug]

        metrics:
          receivers: [otlp, mysql]
          processors: [memory_limiter, batch]
          exporters: [prometheus, debug]