apiVersion: v1
kind: Service
metadata:
  name: otel
  labels:
    com.job.service: otel
spec:
  type: NodePort
  selector:
    app: otel
  ports:
  - name: grpc
    port: 4317
    targetPort: 4317
    nodePort: 30005
  - name: http
    port: 4318
    targetPort: 4318
    # sem nodePort, fica como ClusterIP
  - name: metrics
    port: 8888
    targetPort: 8888
    # sem nodePort