apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-claim
  labels:
    com.job.service: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi