apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    com.job.service: localstack-claim
  name: localstack-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi