apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
data:
  AWS_ACCESS_KEY_ID: 'dGVzdA=='
  AWS_SECRET_ACCESS_KEY: 'dGVzdA=='
  AWS_SESSION_TOKEN: ''
  AWS-ACCOUNT: 'MDAwMDAwMDAwMDAw'