apiVersion: apps/v1
kind: Deployment
metadata:
  name: k6
  labels:
    app: k6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k6
  template:
    metadata:
      labels:
        app: k6
    spec:
      containers:
      - name: k6
        image: grafana/k6:latest
        command: ["k6", "run", "/scripts/script.js"]
        volumeMounts:
        - name: k6-scripts
          mountPath: /scripts
        env:
        - name: K6_OUT
          value: "prometheus=http://prometheus:9090"  # Integração com Prometheus (opcional)
        envFrom:
        - configMapRef:
            name: k6-env
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: k6-scripts
        configMap:
          name: k6-script