apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-pv-claim
  labels:
    com.job.service: ollama-ia
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi