apiVersion: v1
kind: Service
metadata:
  name: ollama
  labels:
    com.job.service: ollama
spec:
  type: NodePort
  ports:
    - port: 11434
      targetPort: 11434
      nodePort: 30007
  selector:
    com.job.service: ollama