apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin-deployment
  labels:
    com.job.service: zipkin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
      - name: zipkin
        image: openzipkin/zipkin:latest
        ports:
        - containerPort: 9411
        env:
        - name: STORAGE_TYPE
          value: "mem"
        livenessProbe:
          httpGet:
            path: /health
            port: 9411
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 9411
          initialDelaySeconds: 15
          periodSeconds: 10