apiVersion: v1
kind: Service
metadata:
  name: zipkin-service
  labels:
    com.job.service: zipkin
spec:
  type: NodePort
  selector:
    app: zipkin
  ports:
    - port: 9411
      name: http
      targetPort: 9411
      nodePort: 30411   # Porta de acesso externo (ajuste se necessário)