apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: mysql-pv-claim
  labels:
    com.job.service: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi