apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    com.job.service: mysql-service
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30001
  selector:
    com.job.service: mysql-db
    tier: mysql
