apiVersion: v1
kind: Service
metadata:
  name: tempo-service
spec:
  selector:
    app: tempo
  ports:
    - name: http
      port: 3200
      targetPort: 30200
    - name: otlp-grpc
      port: 4317
      targetPort: 30317
    - name: otlp-http
      port: 4318
      targetPort: 30318